version: "3.9"

services:
  node-service:
    build:
      context: ./node-service
    container_name: node-service
    environment:
      - PORT=3000
      - JWT_SECRET=xK9fR7p2zQ8vL3wT6bN0gH4mC1yP5sD9
    ports:
      - "3000:3000"

  go-service:
    build:
      context: ./go-service
    container_name: go-service
    environment:
      - PORT=8080
      - NODE_API_URL=http://node-service:3000
      - JWT_SECRET=xK9fR7p2zQ8vL3wT6bN0gH4mC1yP5sD9
    ports:
      - "8080:8080"
    depends_on:
      - node-service
